# Generated by Django 3.1.7 on 2021-03-30 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payrollApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('dateRecorded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='process',
            name='price_positive',
        ),
        migrations.AddField(
            model_name='completedprocess',
            name='employeeId',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='payrollApp.employee'),
        ),
        migrations.AddField(
            model_name='completedprocess',
            name='processId',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='payrollApp.process'),
        ),
    ]
