# Generated by Django 3.1.7 on 2021-04-05 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollApp', '0003_auto_20210330_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='orderId',
            new_name='orderID',
        ),
        migrations.AlterField(
            model_name='completedprocess',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message="Quantity can't be less than 1")]),
        ),
    ]
