# Generated by Django 3.1.7 on 2021-04-05 15:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payrollApp', '0004_auto_20210405_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=100, validators=[django.core.validators.MinValueValidator(0, message="Salary can't be less than 0")])),
                ('notes', models.TextField(blank=True, null=True)),
                ('lastModified', models.DateTimeField(auto_now=True)),
                ('employeeID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payrollApp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.DateField()),
                ('status', models.IntegerField(choices=[(2, 'Late'), (1, 'On time'), (3, 'Absent'), (4, 'On leave')])),
                ('employeeID', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='payrollApp.employee')),
            ],
        ),
    ]
