# Generated by Django 3.1.7 on 2021-04-06 13:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payrollApp', '0005_attendance_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dailySalary', models.DecimalField(decimal_places=2, max_digits=100, validators=[django.core.validators.MinValueValidator(0, message="Salary can't be less than 0")])),
                ('notes', models.TextField(blank=True, null=True)),
                ('lastModified', models.DateTimeField(auto_now=True)),
                ('employeeID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payrollApp.employee')),
            ],
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='dates',
            new_name='date',
        ),
        migrations.AddField(
            model_name='attendance',
            name='percentage',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0, message="Can't be less than 0"), django.core.validators.MaxValueValidator(100, message="Can't be greater than 100")]),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.IntegerField(choices=[(1, 'On time'), (3, 'Absent'), (2, 'Late')]),
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
