# Generated by Django 3.1.7 on 2021-04-06 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollApp', '0006_auto_20210406_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.IntegerField(choices=[(3, 'Absent'), (1, 'On time'), (2, 'Late')]),
        ),
        migrations.AlterField(
            model_name='dailysalary',
            name='dailySalary',
            field=models.DecimalField(decimal_places=2, max_digits=100, validators=[django.core.validators.MinValueValidator(0, message="Daily salary can't be less than 0")]),
        ),
    ]
