# Generated by Django 3.1.7 on 2021-04-08 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payrollApp', '0007_auto_20210407_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
    ]
