# Generated by Django 3.1.7 on 2021-04-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollApp', '0008_remove_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenttype',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
