# Generated by Django 3.1.7 on 2021-04-08 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payrollApp', '0009_auto_20210408_2305'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employeeID', 'date')},
        ),
    ]
