# Generated by Django 3.1.7 on 2021-04-22 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payrollApp', '0011_auto_20210409_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='employeeID',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='payrollApp.employee'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employeeID',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='payrollApp.employee'),
        ),
        migrations.AlterField(
            model_name='completedprocess',
            name='employeeID',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='payrollApp.employee'),
        ),
        migrations.AlterField(
            model_name='completedprocess',
            name='processID',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='payrollApp.process'),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='employeeID',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='payrollApp.employee'),
        ),
        migrations.AlterField(
            model_name='process',
            name='orderID',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='payrollApp.order'),
        ),
    ]
